Repository 100-hours-a-week/20-real-ai, pull requests merged in 2025-06, with the labels that each got.

#101 Feat/wiki news/82
  app/api/router.py
  app/api/v1/controllers/discordnews_controller.py
  app/api/v1/controllers/notice_controller.py
  app/api/v1/endpoints/chat_router.py
  app/api/v1/endpoints/discordnews_router.py
  app/api/v1/endpoints/notice_router.py
  app/api/v2/controllers/wikinews_controller.py
  app/api/v2/endpoints/wikinews_router.py
  app/main.py
  app/models/llm_client.py
  app/models/prompt_template.py
  app/models/qwen3_loader.py
  app/schemas/wikinews_schema.py
  app/services/discordnews_service.py
  app/services/notice_service.py
  app/services/wikinews_service.py
  app/utils/s3_uploader.py
  scripts/upload_to_gcs.py
Labels: ✨ Feature

#105 🐛 fix: MarkdownHeaderTextSplitter 기반 문서 분할 함수 입력 오류 수정
  scripts/create_vectorstore.py
Labels: 🐞 BugFix

#142 ♻️ refactor: JSON 파싱 실패 시 HTTP 500 반환하도록 컨트롤러 예외 처리 개선
  app/api/v1/controllers/discordnews_controller.py
  app/api/v1/controllers/notice_controller.py
  app/api/v2/controllers/wikinews_controller.py
  app/services/chat_service_v3.py
Labels: 🔨 Refactor

#143 ♻️ refactor: JSON 파싱 실패 시 HTTP 500 반환하도록 컨트롤러 예외 처리 개선
  app/api/v1/controllers/discordnews_controller.py
  app/api/v1/controllers/notice_controller.py
  app/api/v2/controllers/wikinews_controller.py
  app/services/chat_service_v3.py
Labels: 🔨 Refactor

#147 ✨ feat: ‘최근/최신’ 키워드 자동 처리 및 리트리버 로직 리팩토링
  app/api/v1/controllers/discordnews_controller.py
  app/api/v1/controllers/notice_controller.py
  app/api/v2/controllers/wikinews_controller.py
  app/api/v3/controllers/chat_controller.py
  app/core/date_utils.py
  app/core/document_loader.py
  app/core/recent_docs_cache.py
  app/core/retriever_factory.py
  app/models/llm_client.py
  app/models/prompt_template.py
  app/services/chat_service.py
  app/services/chat_service_v2.py
  app/services/chat_service_v3.py
  app/services/wikinews_service.py
  docs/notice.md
  scripts/create_vectorstore.py
Labels: ✨ Feature
