Repository 100-hours-a-week/20-real-ai, pull requests merged in 2025-05, with the labels that each got.

#78 ✨ feat: LangSmith 기반 챗봇/RAG/요약 기능 실행 추적 로깅 구현
  app/api/v1/controllers/chat_controller.py
  app/api/v1/controllers/discordnews_controller.py
  app/api/v1/controllers/notice_controller.py
  app/api/v1/endpoints/chat_router.py
  app/core/llm_client.py
  requirements.txt
Labels: ✨ Feature

#79 ✨ feat : Qwen3-AWQ 모델 전환 및 날짜 인식 기능 추가
  app/core/date.py
  app/core/llm_client.py
  app/model/qwen2_5_loader.py
  requirements.txt
Labels: ✨ Feature

#92 🐛 fix: userId 타입을 int로 변경
  app/core/chat_history.py
  app/schemas/chat_schema_v2.py
  app/services/chat_service_v2.py
Labels: 🐞 BugFix

#94 Refactor/logging/80
  app/api/v2/controllers/chat_controller.py
  app/models/llm_client.py
  app/services/chat_service_v2.py
  app/services/discordnews_service.py
  app/services/notice_service.py
Labels: 🔨 Refactor
